name      = "Give the Ring to the Seas"
priority  = "Low"
imgs      = []
claimants = []
reviewers = []
files     = []
releases  = ["Tutorial"]
description = """
**Location:** Tutorial Ship

**Description:**<br>
In the location, there will be NPC called "worried man" and option to "search for stuff at the deck". If you talk with worried man,
he will reveal his struggles: he lost his ring, given by his wife, and he is now in utter panic that this ring dropped to the sea.
He begs us to search for it, as it may still be somewhere on deck.<br>
"Search stuff at the deck" should return us the chance of finding ring - it should be small chance, but it should be possible
(even without talking + if we find the ring, we should not be able to find it again, put invisible event here).

Once we come back with ring to the man, we can tell him we found it. He will then offer us one of two prices:
- 200 baedoorian pounds
- [Fall of Gods magazine](../../../../files/claims/ioa/[Pages]/The%20Fall%20of%20Gods%20(412NE_1).html)

He will suggest us to take the money, as magazine is worth more, but if we would like to get such collectible item, we will be able to.

If we decide to keep the ring, it will be **silver ring with lapis embbed**, without any enchantments or upgrades. It should be worth more than
200 pounds, but not crazily, so taking it won't give us huge benefits.

**NPC background:** the guy can be avant-garde lover, and there could be dialogue revealing a lot of lore related to West Baedoor
theatres.

**Some notes from GitHub claim:**
I think it'd be interesting - if technically possible - to make it accessible via different means.
You could possibly pickpocket the person from #48 to get keys to his cabin and the cabin could
contain the magazine (normally you couldn't access it without getting key, as lock would be impossible to open,
or you can make it also openable with very high difficulty).

This however makes two issues possible if #48 is completed and magazine is claimed:
- magazine should disappear from cabin, so it isn't possible to get two of those
  (interesting case that takes on both chests generating when you open them, not
  when location starts - for better flexibility - or that chests should be able to be edited via quests,
  but this is more bug-friendly [quest items could be easier to manage tho])
- if magazine was taken out earlier, either the sailor should not be able to offer you it anymore,
  or have separate section where it goes to cabin and then comes back to you screaming that it got
  stolen (second option is better for bugproofing reasons, as it shows you outcome of your actions + is very
  simple to code and I can't see any bugs coming from it, unlike first option)
"""