Avatar  = "https://images.cara.app/production/profiles/ec3c4a24-ef4c-4e19-9e64-124dcf91c2ef/blekmetlowakari.png"
Website = "https://cara.app/skeletontonguedworld"
Faction = ""
Tier    = 2
Roles = [
    # Concept Artist, Asset Dev, Zin Contributor, Linguist
]
Projects = [
    "Isle of Ansur"
]
Description = """
"""