# contributors listed
Cicero             = "https://next.nexusmods.com/profile/CiceroTR"
# non-listed contributors or devs
DylanVHS           = ""
Feighten           = ""
JackimoffWackimoff = ""
LilianaUnfolded    = ""
MammaHyena         = ""
MarionetteModder   = "" # however she was called initally...
Meadhainnigh       = ""
Revenant           = ""
Tammilisake        = ""
TotalBlackSmith    = ""
Tristior           = ""
# ehhhh
WanderingIterator  = ""
Kynesifnar         = ""